markdown: redcarpet
title : Matt Jordan
production_url : http://matthewbjordan.me
description: Randomized
author :
  name : Matt Jordan
  github : mbjordan
  twitter : matthewbjordan
  email: mbj755@gmail.com
auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", 'sass', 'watch.sh', 'style.scss'] # files to exclude
