markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
title : Matt Jordan
production_url : http://matthewbjordan.me
description: Randomized
author :
  name : Matt Jordan
  github : mbjordan
  twitter : matthewbjordan
  email: mbj755@gmail.com
exclude: ["Gemfile", "Gemfile.lock", 'sass', 'watch.sh', 'style.scss'] # files to exclude
