pygments: true
title : Matt Jordan
production_url : http://matthewbjordan.me/
description: Randomized
author :
  name : Matt Jordan
  github : mbjordan
  twitter : matthewbjordan
  email: mbj755@gmail.com
