title : Matt Jordan
production_url : http://matthewbjordan.me
description: Randomized
author :
  name : Matt Jordan
  github : mbjordan
  twitter : honyovk
  email: mbj755@gmail.com
exclude: ["Gemfile", "Gemfile.lock", 'sass', 'watch.sh', 'style.scss'] # files to exclude
markdown: kramdown
